### PR TITLE
More Robust Version of Viewport Placement

### PR DESCRIPTION
**Pull request by thazell**
Extracted from Gui's and eirannejad work on pyRevit CopyState and Paste
State

### CODE REVIEW

**Comment by gtalarico** [comment]
@thazell where did you pull this code from?
Noticed is one of the old versions that had my personal email from in it. 
I am trying to clean those out as I started getting a lot of spam after including it the first time

**Comment by thazell** [comment]
I grabbed it form the pyRevitTools "Copy State" and "Paste State"

**Comment by gtalarico** [comment]
@thazell 
I have replaced the script with a new version built from scratch, so I am closing this out with no merge.

This is substantially shorter than the the version you supplied, 
but seems to be working just as well. Let me know if you run into any edge cases.

It uses the relative position of the project base point on the viewport to match, viewport title, annotation crop, etc.

https://github.com/gtalarico/pyrevitplus/commit/90aa34cf36aacdbe242d48e5ed1ec8af844fde05#diff-7c647bff99e456fb0079a55aa0298f76
https://github.com/gtalarico/pyrevitplus/commit/90aa34cf36aacdbe242d48e5ed1ec8af844fde05#diff-df48f042a64c283499e514f6255f356d

**Comment by thazell** [comment]
That's clever! I like the use of the project base point as a base location :)

**Pull request closed without merging**
