### PR TITLE
Schedules and viewport cliping

### PR DESCRIPTION
**Pull request by ejs-ejs**
This is the initial version to support:
- save/restore viewport clipping
- save/restore schedule position

Tested on Revit API 2020, and some projects (270 sheets and counting).

### CODE REVIEW

**Comment by gtalarico** [comment]
Thank you!

**Comment by ejs-ejs** [comment]
2020-08-08 01:25, Gui Talarico rašė:
>
> Thank you!
>

I was standing on the shoulders of the giants

:)

-- 
cheers
Eugenijus Januškevičius

**Comment by gtalarico** [comment]
Nice work @ejs-ejs 
btw you are welcome to take over this repo if it interests you and I can add you as repo maintainer.
I haven't been doing revit dev in a while so it's been pretty stale and hard for me to contribute.

**Comment by gtalarico** [comment]
> I was standing on the shoulders of the giants
That's way too generous. We all just need to thank @eirannejad and Daren from the original revit python shell :)

**Pull request merged**
