### PR TITLE
Adding export to LibreOffice Calc 

### PR DESCRIPTION
**Pull request by PMoureu**
i wondered if these changes could be useful to other users ?

### CODE REVIEW

**Comment by gtalarico** [comment]
thanks @PMoureu !

I have a new version of this has some improvements, including allowing user to add a custom path when one of the defauls is not found, as well as opening in excel from a selected schedule on a sheet.
My fault for not keeping the repo fresh.

I will try to reconcile those with some of your suggestions and merge when i get a chance, ok?

**Comment by PMoureu** [comment]
OK, thanks ! 

The goal was to open another door, i can't tell how many people would use it.
Except this, the main fixes are :
- avoid '/' in ViewName and wrap the element.Export method in a try/except
- keep window opened with multiple selected schedules, in case some failed

**Comment by gtalarico** [comment]
@PMoureu 
I have replaced the script with an improved version I had.
It addresses both of your suggestions:
1. All Non alpha numberic characters are eliminated
2. Added Libre office path

It stores paths in a local file, and when it's not found, it prompts user to add a new path.

**Comment by PMoureu** [comment]
Thanks,  nice workaround ! 
It throws some errors in specific cases, i suggest those changes : 
- check the config file before opening
- get schedule from schedulesheetinstance  (no ViewName)  // the fix allows to select schedules on a ViewSheet
- replacing the editor name in the command

i tested this patch in example :
https://github.com/PMoureu/pyrevitplus/blob/patch/pyRevitPlus.tab/Misc%20Tools.panel/Open%20In%20Excel.pushbutton/script.py

**Comment by gtalarico** [comment]
https://github.com/gtalarico/pyrevitplus/commit/bf702b6f83cefc00ceb1936943b4c9d0238f316d#diff-18359c16a2b863e5a3cb34a4152ec408

**Pull request closed without merging**
